---


- hosts: all
  become: true
  tasks:
  - name: install apache2  and php module packages
    package : 
      name: 
        - "{{apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu" , "Debian" , "CentOS"]