---


- hosts: all
  become: true
  tasks:

  - name: update resposiroty index 
    apt : 
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu" , "Debian" ]

  - name: install apache2  and php module packages
    apt : 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in [ "Ubuntu" , "Debian" ]