---


- hosts: all
  become: true
  tasks:

  - name: update resposiroty index 
    apt : 
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu" , "Debian" ]

  - name: remove apache2 package php module
    apt : 
      name: 
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution in [ "Ubuntu" , "Debian" ]
      