---


- hosts: web_servers
  become: true
  tasks:
  - name: install apache2  and php module packages
    package : 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu" , "Debian" , "CentOS"]
  - name: copy default_site.html file to the webserver
    tags: apache,apache2,web
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: start apache servers
    tags: apache,apache2,web
    service: 
      name: apache2
      state: started
      enabled: yes

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb
    package : 
      name: 
        - mariadb-server
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Ubuntu" , "Debian" , "CentOS"]

- hosts: file_servers
  become: true
  tasks:
  - name: install samba
    package : 
      name: 
        - samba
        - unzip
      state: latest
      update_cache: yes
  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    when: ansible_distribution in [ "Ubuntu" , "Debian" , "CentOS"]
